server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
      
liquibase:
  enabled: true
  change-log: classpath:liquibase/changelog.xml
---

spring:
  profiles: test
    
server:
  port: 8090 